### ISSUE TITLE
Link先が404です。

### ISSUE THREAD

**Issue by masakinihirota** [Nextjs-ja-translation/Nextjs-ja-translation-docs#145]
<ul>
    <li><a href="/examples/with-zones">マルチゾーン</a></li>
  </ul>

↓
リンク先を修正

  <ul>
    <li><a href="https://github.com/vercel/next.js/tree/canary/examples/with-zones">マルチゾーン</a></li>
  </ul>

**Comment by yokinist** [comment]
ご報告ありがとうございます！
リンク先が404であることを確認できたので、 #147 にて修正のプルリクエストを送りました
