### ISSUE TITLE
リポジトリの変更 自動遷移

### ISSUE THREAD

**Issue by masakinihirota** [Nextjs-ja-translation/Nextjs-ja-translation-docs#146]
https://github.com/zeit/next.js
のように「zeti」を含んでいるURLはすべて
↓
https://github.com/vercel/next.js
と「vercel」に変換されます。

検索結果140件 zeitで検出されます。

**Comment by yokinist** [comment]
ご報告ありがとうございます！
こちらについては現在進行系で翻訳が進んでいるので、翻訳完了次第まとめて置き換え対応したいと思います！
少々お待ちください 🙇
