### ISSUE TITLE
旧サイトのクローズ

### ISSUE THREAD

**Issue by 5t111111** [Nextjs-ja-translation/Nextjs-ja-translation-docs#183]
移行前の旧サイトがまだ生存していて検索上位に表示されているため、クロージングの対応したいと思います。
(もっと早くやるべきでしたね、すみません 🙏 )

## やること

- 旧サイト ( https://nextjs-docs-ja.netlify.app ) から新サイト ( https://nextjs-ja-translation-docs.vercel.app ) へ 301 リダイレクトを設定
- わかりやすいように、以下の今度利用されないリポジトリを read-only アーカイブ化
  - https://github.com/Nextjs-ja-translation/nextjs-docs-ja 
  - https://github.com/Nextjs-ja-translation/nextjs-docs-ja-omegat

**Comment by 5t111111** [comment]
@hiro08gh 異論なければやっちゃいます。いかがでしょうか？

**Comment by yokinist** [comment]
@5t111111 ありがとうございます！自分は賛成です！

**Comment by 5t111111** [comment]
@yokinist ありがとうございます！
やっちゃいました！

https://nextjs-docs-ja.netlify.app にアクセスすると新サイトに行くようになっています。

**Comment by yokinist** [comment]
@5t111111 
自分の方でも確認できました！ご対応ありがとうございました🙏
